### ISSUE TITLE
Missing daily dozen and 21 tweaks items

### ISSUE THREAD

**Issue by jcrmatos** [nutritionfactsorg/daily-dozen-android#229] opened 2023-04-30 10:30 UTC
Hello,

I'm using the latest version (22.1) in Portuguese (pt-PT) and noticed that there are some Daily Dozen items missing vs the list in the website (https://nutritionfacts.org/daily-dozen/).
The missing items are: Other fruits, Cruciferous Vegetables, Other Vegetables, Herbs and Spices, Whole Grains.

On the 21 tweaks there are also some missing items: Enjoy Undistracted Meals, Follow the Twenty-Minute Rule, Black Cumin (Nigella sativa) (1/4 tsp), Ground Ginger (1 tsp) or Cayenne Pepper (1/2 tsp), Get Sufficient Sleep.

Thanks,

JM

**Comment by slavick** [comment] 2024-02-04 17:36
Closing this as I cannot reproduce the issue.

**Closed by slavick** 2024-02-04 17:36 UTC
