### ISSUE TITLE
turmeric?

### ISSUE THREAD

**Issue by jpritikin** [nutritionfactsorg/daily-dozen-android#17] opened 2016-06-25 01:44 UTC
Why isn't there a separate checkmark for turmeric?

**Comment by chrisbryant** [comment] 2016-06-26 20:55
Doesn't it just fall under "Spices"?

**Comment by jpritikin** [comment] 2016-06-27 02:29
Turmeric has some unique benefits, [search](http://nutritionfacts.org/?fwp_search=turmeric&fwp_content_type=video) You can't just exchange dill for turmeric and expect to get the same benefit. I don't have the book in front of me, but I recall that Dr Greger book specifically recommends consumption of 1/4 teaspoons of turmeric a day.

**Comment by christirichards** [comment] 2016-06-28 08:35
Turmeric is listed under spices.  Anything else is getting out of scope for the current app and doesn't fall in line with the Daily Dozen theme.

**Closed by christirichards** 2016-06-28 08:35 UTC

**Comment by jpritikin** [comment] 2016-07-07 10:24
I just got my latest lipid panel back. I don't exercise enough, but turmeric has some unique benefits that can compensate for sedentary life, see [turmeric vs exercise](http://nutritionfacts.org/video/heart-of-gold-turmeric-vs-exercise/). This seemed to show in my lipid panel numbers. I got the best numbers that I've seen in a year. I've tried following all of Dr Greger's recommendations, but turmeric made one of the biggest single differences so far. I haven't done a crossover study yet, but I will try when I have the opportunity. I urge you to reconsider you decision. This app is not just about keeping things simple. It's about teaching the optimal diet. In my opinion, turmeric ought to be given the same importance as flax.

**Comment by MovGP0** [comment] 2016-08-15 20:09
Tumeric is already listed quite prominently in spices.

**Comment by jpritikin** [comment] 2016-08-17 15:31
Dr Greger mentions the "1/4 teaspoon per day" recommendation more than once in his book. Here is one instance,

![screenshot from 2016-08-17 11-29-59](https://cloud.githubusercontent.com/assets/2002771/17742452/16954ee6-646e-11e6-8a6a-87defe547948.png)

**Comment by jpritikin** [comment] 2016-08-17 15:34
Here's another one:

![screenshot from 2016-08-17 11-33-21](https://cloud.githubusercontent.com/assets/2002771/17742569/7fcd82c0-646e-11e6-95c1-4cd66bc7501e.png)

**Comment by jpritikin** [comment] 2016-08-17 15:36
At the beginning of the chapter, too:

![screenshot from 2016-08-17 11-35-25](https://cloud.githubusercontent.com/assets/2002771/17742632/d1f53e12-646e-11e6-9974-773d8fd9b092.png)

**Comment by christirichards** [comment] 2016-08-18 05:29
Again, this is out of the scope of the current app and the continued emphasis on this issue has become pedantic.  You are welcome to fork the repo and make a secondary checkbox for yourself.  The issue is dead.
