### ISSUE TITLE
Reminder notification shows up at wrong time

### ISSUE THREAD

**Issue by kartikg3** [nutritionfactsorg/daily-dozen-android#171] opened 2021-04-13 12:07 UTC
I think this started happening since the latest update from the playstore (update from April 3rd 2021).

I have always had my reminder set at 8 pm, but the reminder notification shows up at 8 am. Even if I flip the time it still shows up at 8 am. I tried deleting all reminders and added 2 reminders: 8 am and 8 pm, but it still only shows up at 8 am.

I am on an android LG G6 phone.

Live by the app otherwise, wonderful app. Thanks for the hard work.

**Comment by slavick** [comment] 2021-04-13 15:46
Thanks for the bug report. What version of Android are you running? Are you using 12 hour or 24 hour time?

**Comment by slavick** [comment] 2021-05-16 21:20
Closing this as I am unable to reproduce the bug and have not received any other reports of this issue.

**Closed by slavick** 2021-05-16 21:20 UTC

**Comment by kartikg3** [comment] 2021-05-22 12:24
Thanks for trying to replicate it.

I just tried uninstalling and reinstalling
 I see the same issue. Reminds me at 8 am when I set it to 8 pm.

I have an LG G6 running Android version 9. I use 12 hour time.

**Comment by kartikg3** [comment] 2021-05-22 12:26
Can we please keep this issue open? I really love the app, am an ambassador for it as well, and would like this fixed at some point.

**Comment by kartikg3** [comment] 2021-05-22 12:39
Is there a way to "start fresh" like clearing the preferences?

**Comment by kartikg3** [comment] 2021-05-22 12:56
I can confirm that this started happening after the update that enabled multiple reminders. Hopefully that gives some clues as to where the bug may be.
